"""
Local p4a recipe override: pygame 2.1.3 with Python 3.11 compatibility patches.

Problems
--------
pygame 2.1.3's src_c/_sdl2/sdl2.c was generated by an old Cython version
against Python 3.9 internals.  Python 3.11 broke/removed all of these:

  * #include "longintrepr.h"   -> moved to cpython/longintrepr.h
  * PyCode_New() argument count changed (15 -> 17)
  * PyFrameObject struct became opaque
  * tstate->recursion_depth removed (renamed recursion_remaining)
  * CO_NOFREE flag removed

Fix
---
We keep the exact version / URL / sha256 from the built-in pygame recipe
so all p4a patches and build flags stay intact, and we add a
prebuild_arch() step that replaces sdl2.c with a minimal Python 3.11-safe
stub module.  Our game never uses pygame._sdl2, so an empty module is fine.
"""

import importlib.util as _ilu
import os as _os
import sys as _sys

# ── Load the built-in 'pygame' recipe under a private module name ─────────────
# We cannot do  from pythonforandroid.recipes.pygame import ...  because p4a
# registers OUR file as sys.modules['pythonforandroid.recipes.pygame'] before
# executing it, which would create a circular import.  Loading by file path
# under a different name sidesteps the problem entirely.
import pythonforandroid as _p4a

_builtin_path = _os.path.join(
    _os.path.dirname(_p4a.__file__), 'recipes', 'pygame', '__init__.py'
)
_spec = _ilu.spec_from_file_location('_pygame_builtin_recipe', _builtin_path)
_mod  = _ilu.module_from_spec(_spec)
_sys.modules['_pygame_builtin_recipe'] = _mod
_spec.loader.exec_module(_mod)

_Base = _mod.recipe.__class__   # the real PygameRecipe from p4a


# Minimal C stub for pygame._sdl2.sdl2.
# The real Cython-generated file uses Python 3.9 internal APIs that were
# removed in Python 3.11.  This stub creates an importable-but-empty module
# so setup.py compiles without errors.  The game never calls pygame._sdl2.
_SDL2_STUB = """\
#include <Python.h>

static PyMethodDef _sdl2_methods[] = { {NULL, NULL, 0, NULL} };

static struct PyModuleDef _sdl2_moduledef = {
    PyModuleDef_HEAD_INIT,
    "sdl2",   /* name */
    NULL,     /* docstring */
    -1,       /* per-interpreter state size */
    _sdl2_methods
};

PyMODINIT_FUNC PyInit_sdl2(void) {
    return PyModule_Create(&_sdl2_moduledef);
}
"""


# ── Override ──────────────────────────────────────────────────────────────────
class PygameRecipe(_Base):
    name = 'pygame'   # keep the same recipe name

    def prebuild_arch(self, arch):
        import os
        super().prebuild_arch(arch)

        sdl2_c = os.path.join(
            self.get_build_dir(arch.arch), 'src_c', '_sdl2', 'sdl2.c'
        )
        if not os.path.exists(sdl2_c):
            print(f'[pygame patch] sdl2.c not found at {sdl2_c}, skipping')
            return

        # Replace the Cython-generated sdl2.c with a minimal Python 3.11-safe
        # stub.  The original file uses ~10 Python 3.9 internal C APIs that
        # were all removed or restructured in Python 3.11 (PyCode_New arity,
        # opaque PyFrameObject, missing recursion_depth/CO_NOFREE, etc.).
        with open(sdl2_c, 'w', encoding='utf-8') as fh:
            fh.write(_SDL2_STUB)
        print('[pygame patch] Replaced sdl2.c with Python 3.11-safe stub '
              '(pygame._sdl2 is unused by this game)')


recipe = PygameRecipe()
