"""
Local p4a recipe override: pygame 2.1.3 with Python 3.11 compatibility patches.

Problems
--------
All Cython-generated files under pygame 2.1.3's src_c/_sdl2/ were built
against Python 3.9 internals that were removed/changed in Python 3.11:

  * #include "longintrepr.h"   -> moved to cpython/longintrepr.h
  * PyCode_New() argument count changed (15 -> 17)
  * PyFrameObject struct became opaque
  * tstate->recursion_depth removed (renamed recursion_remaining)
  * CO_NOFREE flag removed

Affected files: sdl2.c, audio.c (and potentially others in _sdl2/).

Fix
---
We keep the exact version / URL / sha256 from the built-in pygame recipe
so all p4a patches and build flags stay intact, and we add a
prebuild_arch() step that replaces every .c file under src_c/_sdl2/ with
a minimal Python 3.11-safe stub module.  The game never uses pygame._sdl2,
so empty stub modules are fine for all of them.
"""

import importlib.util as _ilu
import os as _os
import sys as _sys

# ── Load the built-in 'pygame' recipe under a private module name ─────────────
# We cannot do  from pythonforandroid.recipes.pygame import ...  because p4a
# registers OUR file as sys.modules['pythonforandroid.recipes.pygame'] before
# executing it, which would create a circular import.  Loading by file path
# under a different name sidesteps the problem entirely.
import pythonforandroid as _p4a

_builtin_path = _os.path.join(
    _os.path.dirname(_p4a.__file__), 'recipes', 'pygame', '__init__.py'
)
_spec = _ilu.spec_from_file_location('_pygame_builtin_recipe', _builtin_path)
_mod  = _ilu.module_from_spec(_spec)
_sys.modules['_pygame_builtin_recipe'] = _mod
_spec.loader.exec_module(_mod)

_Base = _mod.recipe.__class__   # the real PygameRecipe from p4a


def _make_stub(module_name: str) -> str:
    """Return a minimal Python 3.11-safe C extension stub for the given name."""
    init_func = 'PyInit_' + module_name
    return (
        '#include <Python.h>\n'
        '\n'
        'static PyMethodDef _stub_methods[] = { {NULL, NULL, 0, NULL} };\n'
        '\n'
        'static struct PyModuleDef _stub_moduledef = {\n'
        '    PyModuleDef_HEAD_INIT,\n'
        f'    "{module_name}",\n'
        '    NULL, -1, _stub_methods\n'
        '};\n'
        '\n'
        f'PyMODINIT_FUNC {init_func}(void) {{\n'
        '    return PyModule_Create(&_stub_moduledef);\n'
        '}\n'
    )


# ── Override ──────────────────────────────────────────────────────────────────
class PygameRecipe(_Base):
    name = 'pygame'   # keep the same recipe name

    def prebuild_arch(self, arch):
        import os
        super().prebuild_arch(arch)

        sdl2_dir = os.path.join(
            self.get_build_dir(arch.arch), 'src_c', '_sdl2'
        )
        if not os.path.isdir(sdl2_dir):
            print(f'[pygame patch] _sdl2 dir not found at {sdl2_dir}, skipping')
            return

        # Replace every Cython-generated .c file in src_c/_sdl2/ with a
        # minimal Python 3.11-safe stub.  All these files were generated by an
        # old Cython against Python 3.9 internal C APIs that were removed in
        # 3.11 (PyCode_New arity, opaque PyFrameObject, etc.).
        # pygame._sdl2 is the newer high-level SDL2 binding; the game doesn't
        # use it, so empty stub modules are safe.
        for fname in os.listdir(sdl2_dir):
            if not fname.endswith('.c'):
                continue
            mod_name = fname[:-2]   # strip .c suffix
            fpath = os.path.join(sdl2_dir, fname)
            with open(fpath, 'w', encoding='utf-8') as fh:
                fh.write(_make_stub(mod_name))
            print(f'[pygame patch] Stubbed {fname} (pygame._sdl2.{mod_name} unused)')


recipe = PygameRecipe()
